FROM apache/spark-py:v3.4.0

USER root

RUN apt-get update && \
    apt-get install -y python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    pyspark==3.4.0 \
    elasticsearch==8.15.0 \
    torch \
    transformers

RUN mkdir -p /app/model && chmod 755 /app/model